name: CI

on:
  pull_request:
    branches: [main]
  push: 
    branches: [main]

jobs:
  format:
    name: 'Check formatting'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install clang-format python3-yapf yapf3
      - name: Run clang-format on C code
        run: clang-format --style=Chromium src/* include/* bench/*.c
      - name: Run yapf on Python code
        run: yapf3 --recursive test bench
  emulated:
    name: ${{ matrix.arch }} on ${{ matrix.distro}} with ${{ matrix.cc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: ['gcc', 'clang']
        arch: ['aarch64', 'armv7', 'ppc64le', 's390x']
        distro: ['alpine_latest', 'ubuntu20.04']
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Build and test
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          install: |
            case "${{ matrix.distro }}" in
              ubuntu*)
                apt-get update -q -y
                apt-get install -q -y software-properties-common
                add-apt-repository ppa:pipewire-debian/meson-ninja
                apt-get update -q -y
                apt-get install -q -y ${{ matrix.cc }} meson python3-cffi python3-distutils python3-hypothesis python3-pytest-benchmark python3-pytest
                ;;
              alpine*)
                apk update
                apk add ${{ matrix.cc }} meson musl-dev build-base py3-cffi py3-hypothesis py3-pytest-benchmark
                ;;
            esac
          run: |
            CC=${{ matrix.cc }} meson setup build
            cd build
            ninja test
            ninja count-eq-bench
  native:
    name: ${{ matrix.os }} with ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cc: ['gcc', 'clang']
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Install dependencies (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common
          sudo add-apt-repository ppa:pipewire-debian/meson-ninja
          sudo apt-get update
          sudo apt-get install meson python3-cffi python3-hypothesis python3-pytest-benchmark python3-pytest
      - name: Install dependencies (Mac)
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew update
          brew install meson pkg-config libffi
          PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig pip3 install cffi hypothesis pytest-benchmark pytest
      - name: Configure Meson
        run: CC=${{ matrix.cc }} meson setup build
      - name: Build and test
        run: cd build && ninja test
      - name: Benchmark (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cd build && ninja count-eq-bench
  mingw:
    name: MinGW with ${{ matrix.cc }}
    runs-on: windows-latest
    strategy:
      matrix:
        cc: ['gcc', 'clang']
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Set up MinGW
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            git
            ${{ matrix.cc }}
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-python-cffi
            mingw-w64-x86_64-python-hypothesis
            mingw-w64-x86_64-python-pytest-benchmark
            mingw-w64-x86_64-python-pytest
      - name: Checkout base repo
        uses: actions/checkout@v2
      - name: Configure meson
        run: CC=${{ matrix.cc }} meson setup build
      - name: Build and test
        run: cd build && ninja test
